# Generated by Django 3.2.2 on 2021-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('fathers_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('class_enrolled', models.CharField(max_length=10)),
                ('marks', models.FloatField(default=0.0)),
                ('enrollment_date', models.DateField()),
            ],
        ),
    ]
